image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 14
  # install modules
  - npm install

build_script:
  - npm run build:prod:electron

test: off
