image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  matrix:
    - image: Visual Studio 2019
      ps: Install-Product node 14
    - image: Ubuntu2004
      nvm install 14.16.0
    - image: macOS
      nvm install 14.16.0
  - npm install

build_script:
  - npm run build:prod:electron

test: off
