image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - npm install

build_script:
  - npm run build:prod:electron

test: off
