name: InstallAndDeploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - v*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm install
      - name: Build the app
        run: npm run build:prod:electron
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm install
      - name: Build the app
        run: npm run build:prod:electron
#  build_macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Install dependency
#        run: npm install
#      - name: Build the app
#        run: npm run build:prod:electron
